apiVersion: constraints.gatekeeper.sh/v1beta1
kind: debug
metadata:
  name: debug
spec:
  match:
    kinds:
      - apiGroups: ["", "apps"]
        kinds: ["Pod", "Deployment"]
    namespaces: ["default"]
    #excludedNamespaces: []
    #labelSelector: []
    #namespaceSelector: []
  parameters:
    registry: ["quay.io/"]
