apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test
  labels:
    app: test-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: test-app
