apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: registry
spec:
  crd:
    spec:
      names:
        kind: registry
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            registry:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package registry

        violation[{"msg": msg, "details": {}}] {
          some container
          input_containers[container]
          #(, "quay.io/")
          not startswith(container.image, input.parameters.registry)
          msg := sprintf("image '%v' comes from untrusted registry", [container.image])
        }

        # read containers from various inputs

        # kubernetes admission review for kind pod
        input_containers[container] {
            container := input.request.object.spec.containers[_]
        }

        # kubernetes admission review for kind ???
        input_containers[container] {
            container := input.request.object.spec.template.spec.containers[_]
        }


        # deployment manifest
        input_containers[container] {
            input.kind = "Deployment"
            container := input.spec.template.spec.containers[_]
        }